apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: ankur512512/httpservice:latest
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 25m
            memory: 16Mi
        
